### ISSUE TITLE
tgtg.exceptions.TgtgLoginError: (429, b'{"errors":[{"code":"TOO_MANY_REQUESTS","message":""}]}')

### ISSUE THREAD

**Issue by goegol** [Dielee/tgtg-python#1]
Hi!

I think i did to many testing!
Maybe you can catch this error?

 `Traceback (most recent call last):
  File "/home/goegol/tgtg_get_tokens.py", line 15, in <module>
    client.get_items()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 181, in get_items
    self.login()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 160, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (429, b'{"errors":[{"code":"TOO_MANY_REQUESTS","message":""}]}')
`

**Comment by Dielee** [comment]
How long do you waited until you clicked the link in the email ?

**Comment by goegol** [comment]
I got this error directly, but i did lot of testing. so maby i hit the api rate limit?

**Comment by Dielee** [comment]
Jep, thats it! I got this after a large amount of testing. Wait about 10 minutes an try again.
For me, this helps.

**Comment by goegol** [comment]
maybe we can catch the exception and create better error message?

**Comment by Dielee** [comment]
Yes, this would be an option. I will add something to catch this issue!

**Comment by goegol** [comment]
nice thnx!

**Comment by Dielee** [comment]
Done! Closing this issue.
