### ISSUE TITLE
error 403 logging in with tokens on VPS

### ISSUE THREAD

**Issue by TanguyOrtegat** [Dielee/tgtg-python#3]
Hello,

i was happy with the code you made and tested everythinh with my own computer and working fine. When i wanted to push the code on VPS and run it, i got a 403 error. here is what i did:

1. I logged in with email on on desktop and validated with email within 2 min
2. retrieved tokens userid 
3. run code on desktop fine
4. moved all code to VPS
5. run the code and getting error 403

![image](https://user-images.githubusercontent.com/17274032/142662494-546b5b12-f934-4a73-a67d-cb091e5c9077.png)

`raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMANvLq0AVRZSoAiYeHbg==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35560,\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
`
Would there be IP whitlisting or something like that ? becasue i am figuring out how to manage this ...

**Comment by Dielee** [comment]
Seems to be an duplicate with #4
Closing
